// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vthnoxhniporvldavflj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0aG5veGhuaXBvcnZsZGF2ZmxqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MjU0NjQsImV4cCI6MjA3MjIwMTQ2NH0.ojRHXhVRh89tcqSk_61CL5T5TfhgtgFahoxPeI5mIFw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});